# This is a basic workflow to help you get started with Actions
name: Terraform Plan & Apply

# Controls when the workflow will run
on:
  # manual run workflow
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
permissions:
  id-token: write
  contents: read

jobs:
  Apply:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    # Download Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Get Repo ID
      uses: nvdaes/get-repository-id@v1
      with:
        repository: rshihengyi/AWS-Enterprise-Kubernetes-Platform_Terraform-Infra

    - name: Debug OIDC token claims
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -R 'split(".") | .[1] | @base64d | fromjson'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.2.4
      with:
         role-to-assume: arn:aws:iam::${{secrets.AWS_ID}}:role/${{secrets.AWS_OIDC_ROLE}}
         aws-region: us-east-1
         audience: sts.amazonaws.com

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_sso_role: ${{ secrets.SSO_IAM_ROLE }}
        TF_VAR_my_region: ${{ secrets.MY_REGION }}
        TF_VAR_region_a: ${{ secrets.REGION_A }}
        TF_VAR_region_b: ${{ secrets.REGION_B }}

    - name: Check AWS CLI
      run: aws --version

    - name: Verify AWS identity
      run: aws sts get-caller-identity --profile DevUser

    - name: Debug EKS token
      run: aws eks get-token --cluster-name My-Cluster --region us-east-1 --profile DevUser

    - name: Apply Terraform
      run: terraform apply -auto-approve
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_sso_role: ${{ secrets.SSO_IAM_ROLE }}
        TF_VAR_my_region: ${{ secrets.MY_REGION }}
        TF_VAR_region_a: ${{ secrets.REGION_A }}
        TF_VAR_region_b: ${{ secrets.REGION_B }}
        
